name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint (node.js 20 on ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Use node.js 20
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - name: Install npm@v10
        run: npm i -g npm@v10
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Check licenses
        run: npm run jsgl
      - name: Run lints
        run: npm run lint
