name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint (node.js 14 on ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use node.js 14
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Check licenses
        run: npm run jsgl
      - name: Run lints
        run: npm run lint
