name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test (node.js 20 on ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Use node.js 20
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - name: Install npm@v10
        run: npm i -g npm@v10
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Run tests
        run: npm run test
