name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test (node.js 12 on ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Use node.js 12
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 12
      - name: Install npm@v8
        run: npm -g npm@v8
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Run tests
        run: npm run test
