name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test (node.js 14 on ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - name: Use node.js 14
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 14
      - name: Install npm@v8
        run: npm i -g npm@v8
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Run tests
        run: npm run test
